<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@833.va_1c71061486b_">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2759.v87459c4eea_ca_">
    <parentIds>
      <string>27</string>
    </parentIds>
    <id>28</id>
    <startId>26</startId>
  </node>
  <actions>
    <wf.a.BodyInvocationAction plugin="workflow-api@1188.v0016b_4f29881"/>
    <wf.a.TimingAction plugin="workflow-api@1188.v0016b_4f29881">
      <startTime>1659155422810</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1188.v0016b_4f29881">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 127</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>